[metadata]
name = xfastsort2-dynamics
version = 0.1.0
description = HMM/PCA/t-SNE pipelines for TI LFP and spike-derived features
long_description = file: README.md
long_description_content_type = text/markdown
author = Shumao Xu
author_email = shumaoxu@fudan.edu.cn
url = https://github.com/shumao469/stroke
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.9
install_requires =
    numpy
    scipy
    pandas
    scikit-learn
    matplotlib
    tqdm
    hmmlearn

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    xfastsort2-dynamics = xfastsort2_dynamics.cli:main
