[metadata]
name = umap-state
version = 0.1.0
description = UMAP state-space analysis for TI spike/LFP feature time series
long_description = file: README.md
long_description_content_type = text/markdown
author = Shumao Xu
author_email = shumaoxu@fudan.edu.cn
url = https://github.com/shumao469/stroke
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.9
install_requires =
    numpy
    scipy
    pandas
    scikit-learn
    matplotlib
    tqdm
    umap-learn

[options.extras_require]
hdbscan =
    hdbscan
gpu =
    cuml

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    umap-state = umap_state.cli:main
