[server]
headless = true
port = 8502
maxUploadSize = 1900
maxMessageSize = 1900
fileWatcherType = "none"
runOnSave = false
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
